'use client';
import {useEffect,useRef,useState} from 'react';
import {Check,LoaderCircle,Plus,Sparkles} from 'lucide-react';
import {useVocabularyStore} from '@/store/useVocabularyStore';
import {LanguageSelector} from '@/components/ui/Parts';

export default function Add(){
  const s=useVocabularyStore(),ref=useRef<HTMLInputElement>(null);
  const [lang,setLang]=useState(s.selectedStudyLanguage),[word,setWord]=useState(''),[tr,setTr]=useState(''),[cat,setCat]=useState('other'),[session,setSession]=useState(''),[example,setExample]=useState(''),[note,setNote]=useState(''),[msg,setMsg]=useState(''),[suggestions,setSuggestions]=useState<string[]>([]),[loading,setLoading]=useState(false);
  const validSessions=s.sessions.filter(x=>x.language===lang);
  useEffect(()=>{const clean=word.trim();setSuggestions([]);if(clean.length<2)return;const controller=new AbortController();const timer=setTimeout(async()=>{setLoading(true);try{const r=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:clean,sourceLanguage:lang}),signal:controller.signal});const data=await r.json() as {suggestions?:string[];error?:string};if(r.ok)setSuggestions(data.suggestions||[]);else setMsg(data.error||'Не удалось получить перевод.')}catch(e){if((e as Error).name!=='AbortError')setMsg('Переводчик временно недоступен. Можно ввести перевод вручную.')}finally{setLoading(false)}},550);return()=>{clearTimeout(timer);controller.abort()}},[word,lang]);
  const save=(again=false)=>{if(!word.trim()||!tr.trim()){setMsg('Заполните слово и перевод.');return}const sid=session||validSessions[0]?.id||s.addSession(`${lang==='english'?'Английский':'Немецкий'} — ${new Date().toLocaleString('ru')}`,lang);if(s.words.some(w=>w.language===lang&&w.word.trim().toLocaleLowerCase()===word.trim().toLocaleLowerCase())){setMsg('Это слово уже добавлено в ваш словарь.');return}s.addWord({language:lang,word:word.trim(),translationRu:tr.trim(),categoryId:cat,sessionId:sid,example,note,favorite:false,learned:false,correctAnswers:0,wrongAnswers:0,difficulty:'new'});setMsg('Слово сохранено.');if(again){setWord('');setTr('');setExample('');setNote('');setSuggestions([]);setTimeout(()=>ref.current?.focus(),0)}};
  return <div className="max-w-2xl mx-auto"><p className="muted text-sm">Перевод с помощью DeepL</p><h1 className="text-3xl font-black mb-6">Новое слово</h1><div className="card p-5 md:p-7 space-y-5"><LanguageSelector value={lang} onChange={l=>{setLang(l);setSession('');setTr('');setSuggestions([])}}/><label className="block"><span className="font-bold text-sm">{lang==='english'?'Английское':'Немецкое'} слово</span><div className="relative"><input ref={ref} className="mt-2 pr-12" autoFocus value={word} onChange={e=>{setWord(e.target.value);setMsg('')}} placeholder={lang==='english'?'Например, journey':'Например, Reise'} autoComplete="off"/>{loading&&<LoaderCircle aria-label="Получаем перевод" className="absolute right-4 top-5 animate-spin muted" size={20}/>}</div></label>{suggestions.length>0&&<div className="rounded-2xl p-4" style={{background:'var(--mint)',border:'1px solid var(--line)'}}><div className="flex items-center gap-2 text-sm font-bold mb-3"><Sparkles size={17}/>DeepL предлагает</div>{suggestions.map(x=><button type="button" className="btn w-full justify-between mb-2 last:mb-0" style={{background:'var(--card-strong)'}} key={x} onClick={()=>{setTr(x);setMsg('Перевод выбран.')}}><span>{x}</span><Check size={17}/></button>)}</div>}<label className="block"><span className="font-bold text-sm">Перевод на русский</span><input className="mt-2" value={tr} onChange={e=>setTr(e.target.value)} placeholder="Выберите подсказку или напишите свой перевод"/></label><div className="grid sm:grid-cols-2 gap-4"><label><span className="font-bold text-sm">Категория</span><select className="mt-2" value={cat} onChange={e=>setCat(e.target.value)}>{s.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label><span className="font-bold text-sm">Сеанс</span><select className="mt-2" value={session} onChange={e=>setSession(e.target.value)}><option value="">Создать автоматически</option>{validSessions.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label></div><label><span className="font-bold text-sm">Пример употребления</span><input className="mt-2" value={example} onChange={e=>setExample(e.target.value)}/></label><label><span className="font-bold text-sm">Заметка</span><textarea className="mt-2" value={note} onChange={e=>setNote(e.target.value)} rows={2}/></label>{msg&&<p role="status" className="text-sm" style={{color:msg.includes('недействителен')||msg.includes('Заполните')?'var(--danger)':'var(--muted)'}}>{msg}</p>}<div className="grid sm:grid-cols-2 gap-3"><button className="btn secondary" onClick={()=>save(false)}><Check size={18}/>Добавить слово</button><button className="btn primary" onClick={()=>save(true)}><Plus size={18}/>Добавить и продолжить</button></div></div></div>
}
